# Generated by Django 3.2.4 on 2021-07-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
