# Generated by Django 3.2.4 on 2021-07-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_alter_vacancy_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
